# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "usbhid"];
  boot.supportedFilesystems = ["f2fs"];
  environment.systemPackages = [pkgs.f2fs-tools];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/66c240f9-ee0b-43a1-accd-71f66622fd87";
    fsType = "btrfs";
    options = ["subvol=@nix" "compress=zstd"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/66c240f9-ee0b-43a1-accd-71f66622fd87";
    fsType = "btrfs";
    options = ["subvol=@home" "compress=zstd"];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/66c240f9-ee0b-43a1-accd-71f66622fd87";
    fsType = "btrfs";
    options = ["subvol=@" "compress=zstd"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/D72E-A57D";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  fileSystems."/mnt/data" = {
    device = "/dev/disk/by-uuid/8bae9f12-3ffb-4790-961b-aa357e0cfa5a";
    fsType = "f2fs";
    options = [
      "compress_algorithm=zstd"
      "compress_chksum"
      "atgc"
      "gc_merge"
      "lazytime"
      "users"
      "nofail"
      "x-gvfs-show"
    ];
  };

  systemd.tmpfiles.rules = [
    "d /mnt/data 0777 root root - -"
  ];

  zramSwap.enable = true;
  zramSwap.algorithm = "zstd";
  zramSwap.memoryPercent = 50;
  zramSwap.priority = 100;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
