# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/9d2ae108-ec9e-41fb-8242-47e48ffa90f1";
    fsType = "ext4";
  };

  fileSystems."/mnt/data" = {
    device = "/dev/disk/by-uuid/1b192ca5-4c55-4956-a603-b0b13b9085dc";
    fsType = "btrfs";
    options = [
      "users" # Allows any user to mount and unmount
      "nofail" # Prevent system from failing if this drive doesn't mount
      "exec" # Permit execution of binaries and other executable files
      "x-gvfs-show"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/5C0E-8F29";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  systemd.tmpfiles.rules = [
    "d /mnt/data 0777 root root -"
  ];

  swapDevices = [
    {device = "/dev/disk/by-uuid/74362763-fb0a-475c-a11e-8a292bcb51f7";}
  ];
  zramSwap.enable = true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
